/**
 * This code was generated by Builder.io.
 */
import * as React from "react";

function MyComponent(props) {
  return (
    <>
      <div>
        <nav className="text-[white] flex justify-between pr-4 p-2.5">
          <div>Home</div>
          <div>About</div>
          <div>Settings</div>
        </nav>
      </div>
      <div className="flex flex-col relative shrink-0 box-border mt-5 mx-auto">
        <h1>I Did It!1!</h1>
      </div>
    </>
  );
}
